#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intakeMotor,   tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor F = Right Back
//Motor G = Right Front
//Motor H = Left Back
//Motor I = Left Front

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous B - Right
//
// Position robot so it is facing white line. Go towards and line fallow until in front of ramp.
// Check ultrasonic throughout making sure we don't run in to anything. Check again to see if there
// is a robot in the way of bridge. If not, go on bridge. If so, go on other side.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}

//For condensed code, this function serves as an easy way to move all motors forward/backwards
void forward(int power, int distance)
{
	motor[leftMotor] = power;
	motor[rightMotor] = power;


	if(distance != 0)
	{
		//TODO travel for distance
	}
}

//For condensed code, this function serves as an easy way to turn the robot by specifing the two sides power
void turn(int powL, int powR, int distance)
{
	motor[rightMotor] = powR;
	motor[leftMotor] = powL;

	if(distance != 0)
	{
		//TODO travel for distance
	}
}

task main()
{
  initializeRobot();

  while (SensorValue[light] < 90)
  	forward(60, 0);
 turn(-20, 50, 0);
 wait10Msec(80);

	while (SensorValue[light] < 50)
	{
		forward(70, 0);

		if (SensorValue[sonar] < 25)
		{
			turn(-40, 60, 45);
			while (SensorValue[light] != 0)
		  	forward(60, 0);
		}
	}

	nMotorEncoder[leftMotor] = 0;

	while (nMotorEncoder[leftMotor] < -2000)
	{
		forward(70, 0);

		if (SensorValue[sonar] < 25)
		{
			turn(-40, 60, 45);
			while (SensorValue[light] != 0)
		  	forward(60, 0);
		}
	}
}
