#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SensorColor,    sensorCOLORFULL)
#pragma config(Sensor, S4,     SensorSonic,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Motor D = spin
//Servo 1 = tilt

task main()
{

	int serVal = 0;
	bool serv = true;

	while(nNxtButtonPressed != 0)
	{
		servo[servo1] = serVal;

		if (serv)
		{
			nxtDisplayString(1, "Tilt Mode");
			if(nNxtButtonPressed == 2)
				serVal += 5;
			else
				if(nNxtButtonPressed == 1)
					serVal -= 5;
		}
		else
		{
			nxtDisplayString(1, "Spin Mode");
			if(nNxtButtonPressed == 2)
				motor[motorD] = 50;
			else
				if(nNxtButtonPressed == 1)
					motor[motorD] = -50;
				else
					motor[motorD] = 0;
		}

		if(nNxtButtonPressed == 3)
		{
			if (serv)
				serv = false;
			else
				serv = true;
		}
		short out = nMotorEncoder[motorE];
	}

}
