#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SensorColor,    sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     SensorSonic,    sensorSONAR)
#pragma config(Motor,  motorC,          motorc,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//motorE is the spinner

task main()
{
	int x = 1;
	while(x == 1)
	{
		if(nNxtButtonPressed == 2)
		{
			motor[motorC] = 40;
		}
		if(nMotorEncoder[motorC] > 110)
		{
			motor[motorC] = 0;
			x = x + 1;
		}
	}
		if(nNxtButtonPressed == 2)
		{
			motor[motorF] = 40;
		}
		else
		{
			motor[motorF] = 0;
		}
		while(nNxtButtonPressed == 1 && nMotorEncoder[motorF] < 110)
		{
			motor[motorF] = -40;
			if (nMotorEncoder[motorF] < 10)
			{
				motor[motorC] = 40;
				if (nMotorEncoder[motorC] < 110)
				{
					motor[motorC] = 0;
				}
			}
		else
		{
			motor[motorF] = 0;
		}
		while (nNxtButtonPressed == 3)
		{
			motor[motorC] = -40;
			if(nMotorEncoder[motorC] == 0)
			{
				motor[motorC] = 0;
			}
		}
	}
}
