#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     SensorIR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     SensorColor,    sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     SensorSonic,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void liftTo(int encTarget, int threshold, int startPower, int endPower, int tiltPower)
{
	motor[motorE] = 20;
	int encStart = nMotorEncoder[motorE];
	float rate = (startPower - endPower) / abs(encTarget - encStart);

	int encCurr = nMotorEncoder[motorE];
	int powCurr = startPower;

	bool forward = encTarget > encCurr;

	while (!(nMotorEncoder[motorE] < encTarget + threshold && !forward) && !(nMotorEncoder[motorE] > encTarget - threshold && forward))
	{

		if (nMotorEncoder[motorE] != encCurr)// && !passed) //Checks if encoder value moved and adjusts the power
		{
			powCurr += rate * abs(nMotorEncoder[motorE] - encCurr);
			encCurr = nMotorEncoder[motorE];
		}

		if (nMotorEncoder[motorE] > encTarget) //Sets the power based on direction
			motor[motorE] = powCurr * -1;
		else
			motor[motorE] = powCurr;

		if (abs(nMotorEncoder[motorE] - encStart) > 400)
		{
			motor[motorB] = tiltPower;
			motor[motorC] = tiltPower;
		}
		else
		{
			motor[motorB] = tiltPower / -5;
			motor[motorC] = tiltPower / -5;
		}
	}
}


task main()
{

	nMotorEncoder[motorE] = 0; //Reset encoders
	nMotorEncoder[motorC] = 0;
	liftTo(700, 25, 60, 15, 15); //Lifts steadily to encoder value 700
	motor[motorE] = 15; //Continue into stopper
	wait10Msec(110);
	motor[motorE] = 0; //Stop the lift
	while (!(nMotorEncoder[motorC] < -10)) //Dump blocks
	{
		motor[motorC] = -20;
		motor[motorB] = -20;
	}
	motor[motorB] = 0;
	motor[motorC] = 0;
	wait10Msec(50);
	liftTo(500, 80, 50, 10, 1);
	motor[motorE] = 2;
	wait10Msec(200);

}
